import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryProviders } from "@/components/providers/QueryProvider";
import { Providers } from "@/components/providers/Rainbow-Provider";

const geistSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <QueryProviders>
          <Providers>
            {children}
          </Providers>
        </QueryProviders>
      </body>
    </html>
  );
}
